begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions,auth,pg_catalog;
select plan(16);
select has_table('driver_completion_policies');
select columns_are('driver_completion_policies',array['organization_id','require_pod','require_signature','require_document','updated_by','updated_at']);
select is((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.driver_completion_policies'::regclass),true,'RLS forzada en política de finalización');
select has_function('public','driver_has_order_access',array['uuid','text']);
select volatility_is('public','driver_has_order_access',array['uuid','text'],'stable');
select is_definer('public','driver_has_order_access',array['uuid','text'],'helper de asignación protegido');
select has_function('public','execute_driver_transport_operation',array['uuid','uuid','uuid','text','text','jsonb','uuid','uuid']);
select is_definer('public','execute_driver_transport_operation',array['uuid','uuid','uuid','text','text','jsonb','uuid','uuid'],'comando transaccional protegido');
select function_privs_are('public','execute_driver_transport_operation',array['uuid','uuid','uuid','text','text','jsonb','uuid','uuid'],'anon',array[]::text[],'anon no ejecuta comandos');
select function_privs_are('public','execute_driver_transport_operation',array['uuid','uuid','uuid','text','text','jsonb','uuid','uuid'],'authenticated',array['EXECUTE'],'JWT autenticado puede invocar con autorización interna');
select function_privs_are('public','driver_has_order_access',array['uuid','text'],'anon',array[]::text[],'anon no consulta asignaciones');
select policy_roles_are('public','transport_orders','transport_orders_read',array['authenticated'],'RLS de órdenes se aplica a autenticados');
select policy_roles_are('public','transport_notes','notes_read',array['authenticated'],'notas del conductor protegidas');
select is((select count(*)::integer from information_schema.role_table_grants where grantee='authenticated' and table_schema='public' and table_name='driver_completion_policies' and privilege_type<>'SELECT'),0,'frontend no modifica política');
select ok(position('s.revoked_at is null' in pg_get_functiondef('public.execute_driver_transport_operation(uuid,uuid,uuid,text,text,jsonb,uuid,uuid)'::regprocedure))>0,'completion accepts only non-revoked signatures');
select ok(position('s.status' in pg_get_functiondef('public.execute_driver_transport_operation(uuid,uuid,uuid,text,text,jsonb,uuid,uuid)'::regprocedure))=0,'completion does not query a nonexistent signature status');
select * from finish();
rollback;
