begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions,auth,pg_catalog;
select plan(18);
select has_table('transport_executions');
select has_table('transport_incidents');
select has_table('transport_notes');
select has_table('internal_notifications');
select has_view('transport_waiting_times');
select enum_has_labels('public','transport_execution_status',array['pending','driver_notified','heading_to_pickup','arrived_pickup','waiting_pickup','loading','loaded','departed_pickup','in_transit','arrived_delivery','waiting_delivery','unloading','delivered','completed','cancelled']);
select enum_has_labels('public','transport_incident_category',array['delay','breakdown','traffic','customer_absent','wrong_address','missing_goods','damaged_goods','documentation','other']);
select enum_has_labels('public','transport_incident_severity',array['low','normal','high','critical']);
select enum_has_labels('public','transport_incident_status',array['open','in_progress','resolved','closed','archived']);
select col_is_unique('transport_executions','transport_order_id','una ejecución por orden');
select has_index('transport_executions','transport_executions_org_status_idx');
select has_index('transport_incidents','transport_incidents_order_status_idx');
select is((select count(*)::integer from pg_class where relnamespace='public'::regnamespace and relname in('transport_executions','transport_incidents','transport_notes','internal_notifications') and relrowsecurity and relforcerowsecurity),4,'RLS forzada en tablas operativas');
select is((select count(*)::integer from information_schema.role_table_grants where grantee='anon' and table_schema='public' and table_name in('transport_executions','transport_incidents','transport_notes','internal_notifications')),0,'anon sin acceso');
select is((select count(*)::integer from modules where code='transport_execution'),1,'módulo registrado una vez');
select is((select count(*)::integer from plan_modules pm join modules m on m.id=pm.module_id where m.code='transport_execution'),(select count(*)::integer from plans),'todos los planes tienen valor heredable');
select volatility_is('public','phase_c_module_enabled',array['uuid'],'stable');
select is_definer('public','phase_c_module_enabled',array['uuid'],'helper protegido con security definer');
select * from finish(); rollback;
