import { allowedExecutionTransitions, requiredExecutionText } from "@albatrans/domain";
import type { ExecutionStatus, IncidentCategory, IncidentSeverity } from "@albatrans/contracts";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { executeExecutionCommand, loadExecution, type ExecutionDetail } from "../../data/execution-repository";
const labels: Record<ExecutionStatus, string> = { pending: "Pendiente", driver_notified: "Conductor avisado", heading_to_pickup: "Hacia recogida", arrived_pickup: "Llegada a recogida", waiting_pickup: "Esperando carga", loading: "Cargando", loaded: "Cargado", departed_pickup: "Salida de recogida", in_transit: "En tránsito", arrived_delivery: "Llegada a entrega", waiting_delivery: "Esperando descarga", unloading: "Descargando", delivered: "Entregado", completed: "Completado", cancelled: "Cancelado" };
export function ExecutionPage({ organizationId, orderId, platform }: { organizationId: string; orderId: string; platform: boolean }) {
  const [data, setData] = useState<ExecutionDetail | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false), [success, setSuccess] = useState("");
  const refresh = useCallback(async () => { setError(""); try { setData(await loadExecution(organizationId, orderId)); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo cargar la ejecución."); } }, [organizationId, orderId]);
  useEffect(() => { void refresh(); }, [refresh]);
  async function command(resource: "execution" | "incident" | "note", action: "start" | "transition" | "create", values: Record<string, string | boolean | null> = {}, targetStatus?: string) { setBusy(true); setError(""); setSuccess(""); try { await executeExecutionCommand({ organizationId, transportOrderId: orderId, resource, action, values, targetStatus }); setSuccess("Cambio guardado correctamente."); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo guardar."); } finally { setBusy(false); } }
  if (!data && !error) return <main className="list-state" role="status">Cargando ejecución…</main>;
  if (!data) return <main className="list-state error-state" role="alert">{error}</main>;
  const back = platform ? `/platform/organizations/${organizationId}/transport/${orderId}` : `/empresa/transport/${orderId}`;
  return <main className="resource-page execution-page"><header className="resource-header"><div><p className="eyebrow">Ejecución operativa</p><h1>Seguimiento real</h1></div><Link className="button button-secondary" to={back}>Volver a planificación</Link></header>
    {error && <p className="form-error" role="alert">{error}</p>}{success && <p className="form-success" role="status">{success}</p>}
    <section className="panel"><h2>Estado operativo</h2>{!data.execution ? <div className="empty-state"><p>La ejecución todavía no ha comenzado.</p><button className="button" disabled={busy} onClick={() => void command("execution", "start")}>Iniciar ejecución</button></div> : <><p className="execution-current"><span className="status-pill">{labels[data.execution.status]}</span></p><div className="action-row">{allowedExecutionTransitions(data.execution.status).map((status) => <button className={status === "cancelled" ? "button button-danger" : "button"} disabled={busy} key={status} onClick={() => void command("execution", "transition", {}, status)}>{labels[status]}</button>)}</div></>}</section>
    <TimePanel waiting={data.waiting} />
    <div className="execution-grid"><IncidentPanel disabled={!data.execution || busy} incidents={data.incidents} create={(values) => command("incident", "create", values)} /><NotePanel disabled={!data.execution || busy} notes={data.notes} create={(values) => command("note", "create", values)} /></div>
    <section className="panel"><h2>Timeline oficial</h2>{data.timeline.length === 0 ? <p className="empty-state">Sin eventos todavía.</p> : <ol className="timeline-list">{data.timeline.map((event) => <li key={event.id}><strong>{event.event_type}</strong><time>{new Date(event.occurred_at).toLocaleString("es-ES")}</time></li>)}</ol>}</section>
  </main>;
}
function TimePanel({ waiting }: { waiting: ExecutionDetail["waiting"] }) { const values = [["Espera carga", waiting?.waiting_pickup_seconds], ["Espera descarga", waiting?.waiting_delivery_seconds], ["Carga", waiting?.loading_seconds], ["Descarga", waiting?.unloading_seconds], ["Tránsito", waiting?.transit_seconds], ["Total", waiting?.total_seconds]] as const; return <section className="panel"><h2>Indicadores de tiempos</h2><dl className="metric-grid">{values.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{duration(value)}</dd></div>)}</dl></section>; }
function IncidentPanel({ disabled, incidents, create }: { disabled: boolean; incidents: ExecutionDetail["incidents"]; create: (values: Record<string, string | boolean | null>) => Promise<void> }) { const [title, setTitle] = useState(""), [description, setDescription] = useState(""), [category, setCategory] = useState<IncidentCategory>("delay"), [severity, setSeverity] = useState<IncidentSeverity>("normal"); async function submit(event: FormEvent) { event.preventDefault(); await create({ title: requiredExecutionText(title, "Título", 200), description: requiredExecutionText(description, "Descripción", 4000), category, severity }); setTitle(""); setDescription(""); } return <section className="panel"><h2>Incidencias</h2><form onSubmit={(event) => void submit(event)} className="compact-form"><input aria-label="Título de incidencia" placeholder="Título" value={title} onChange={(e) => setTitle(e.target.value)} required/><textarea aria-label="Descripción de incidencia" placeholder="Descripción" value={description} onChange={(e) => setDescription(e.target.value)} required/><select aria-label="Categoría" value={category} onChange={(e) => setCategory(e.target.value as IncidentCategory)}><option value="delay">Retraso</option><option value="breakdown">Avería</option><option value="traffic">Tráfico</option><option value="other">Otra</option></select><select aria-label="Prioridad" value={severity} onChange={(e) => setSeverity(e.target.value as IncidentSeverity)}><option value="low">Baja</option><option value="normal">Normal</option><option value="high">Alta</option><option value="critical">Crítica</option></select><button className="button" disabled={disabled}>Registrar incidencia</button></form>{incidents.length === 0 ? <p className="empty-state">Sin incidencias.</p> : <ul className="simple-list">{incidents.map((item) => <li key={item.id}><strong>{item.title}</strong><span>{item.severity} · {item.status}</span></li>)}</ul>}</section>; }
function NotePanel({ disabled, notes, create }: { disabled: boolean; notes: ExecutionDetail["notes"]; create: (values: Record<string, string | boolean | null>) => Promise<void> }) { const [body, setBody] = useState(""); async function submit(event: FormEvent) { event.preventDefault(); await create({ body: requiredExecutionText(body, "Nota", 4000), note_type: "operational", visible_admin: true, visible_driver: false, visible_customer: false }); setBody(""); } return <section className="panel"><h2>Notas operativas</h2><form onSubmit={(event) => void submit(event)} className="compact-form"><textarea aria-label="Nueva nota" placeholder="Nueva nota" value={body} onChange={(e) => setBody(e.target.value)} required/><button className="button" disabled={disabled}>Añadir nota</button></form>{notes.length === 0 ? <p className="empty-state">Sin notas.</p> : <ul className="simple-list">{notes.map((item) => <li key={item.id}><p>{item.body}</p><time>{new Date(item.created_at).toLocaleString("es-ES")}</time></li>)}</ul>}</section>; }
function duration(value: number | null | undefined) { if (value === null || value === undefined) return "Sin calcular"; const hours = Math.floor(value / 3600), minutes = Math.floor((value % 3600) / 60); return `${hours} h ${minutes} min`; }
