import type { DriverAction, DriverIdentityErrors, DriverIdentityInput, OrganizationDriver, OrganizationDriversResult } from "@albatrans/contracts";
import { normalizeDriverIdentity, validateDriverIdentity } from "@albatrans/domain";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { createOrganizationDriver, loadOrganizationDrivers, runOrganizationDriverAction, updateOrganizationDriver } from "../../data/organization-driver-repository";

const empty: DriverIdentityInput = { email: "", displayName: "", phone: "", locale: "es", timezone: "Europe/Madrid" };
const gateway = { load: loadOrganizationDrivers, create: createOrganizationDriver, update: updateOrganizationDriver, action: runOrganizationDriverAction };
type Gateway = typeof gateway;

export function OrganizationDriversManager({ organizationId, api = gateway, onChanged }: { organizationId: string; api?: Gateway; onChanged: () => Promise<void> }) {
  const [result, setResult] = useState<OrganizationDriversResult | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null); const [form, setForm] = useState<DriverIdentityInput | null>(null); const [editing, setEditing] = useState<OrganizationDriver | null>(null); const [errors, setErrors] = useState<DriverIdentityErrors>({}); const [saving, setSaving] = useState(false); const [acting, setActing] = useState<string | null>(null); const [deleting, setDeleting] = useState<OrganizationDriver | null>(null);
  const refresh = useCallback(async () => { setLoading(true); setError(null); try { setResult(await api.load(organizationId)); } catch (caught) { setError(message(caught)); } finally { setLoading(false); } }, [api, organizationId]); useEffect(() => { void refresh(); }, [refresh]);
  const limitReached = Boolean(result && (result.effectiveLimit === null || result.assignedCount >= result.effectiveLimit));
  function beginCreate() { setEditing(null); setForm(empty); setErrors({}); setError(null); setSuccess(null); }
  function beginEdit(driver: OrganizationDriver) { setEditing(driver); setForm({ email: driver.email, displayName: driver.displayName, phone: driver.phone, locale: driver.locale, timezone: driver.timezone }); setErrors({}); setError(null); setSuccess(null); }
  function update<K extends keyof DriverIdentityInput>(field: K, value: DriverIdentityInput[K]) { setForm((current) => current ? { ...current, [field]: value } : current); setErrors((current) => ({ ...current, [field]: undefined })); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!form) return; const normalized = normalizeDriverIdentity(form); const validation = validateDriverIdentity(normalized); if (!validation.valid) { setErrors(validation.errors); return; } setSaving(true); setError(null); setSuccess(null); try { if (editing) await api.update(organizationId, editing.userId, normalized); else await api.create(organizationId, normalized); setSuccess(editing ? "Conductor actualizado." : "Invitación enviada y conductor creado."); setForm(null); setEditing(null); await refresh(); await onChanged(); } catch (caught) { setError(message(caught)); } finally { setSaving(false); } }
  async function run(driver: OrganizationDriver, action: DriverAction) { setActing(driver.userId); setError(null); setSuccess(null); try { await api.action(organizationId, driver.userId, action); setSuccess(actionMessage(action)); setDeleting(null); await refresh(); await onChanged(); } catch (caught) { setError(message(caught)); if (action === "delete") await refresh(); } finally { setActing(null); } }
  return <section className="detail-section drivers-manager" aria-labelledby="drivers-title"><div className="section-heading"><div><h2 id="drivers-title">Conductores</h2><p>{result ? `${result.assignedCount} asignados · límite ${result.effectiveLimit ?? "sin configurar"}` : "Cargando límite…"}</p></div><button className="button" type="button" disabled={loading || limitReached} onClick={beginCreate}>Nuevo conductor</button></div>
    {limitReached ? <p className="commercial-notice warning">{result?.effectiveLimit === null ? "La empresa no tiene configurado un límite de conductores." : "Se ha alcanzado el límite de conductores del plan."}</p> : null}
    {loading ? <div className="list-state" aria-busy="true">Cargando conductores…</div> : null}{!loading && result?.items.length === 0 ? <p className="list-state">No hay conductores asignados.</p> : null}
    {!loading && result?.items.length ? <div className="administrators-table-wrap"><table className="administrators-table"><thead><tr><th>Conductor</th><th>Estado</th><th>Acceso</th><th>Último acceso</th><th>Creación</th><th>Creado por</th><th>Acciones</th></tr></thead><tbody>{result.items.map((driver) => <tr key={driver.userId}><td><strong>{driver.displayName}</strong><span>{driver.email}</span><small>{driver.phone || "Sin teléfono"}</small></td><td><span className={`status-badge status-${driver.membershipStatus}`}>{driver.membershipStatus}</span></td><td>{driver.invitationPending ? "Invitación pendiente" : driver.accessActive ? "Acceso activo" : "Acceso desactivado"}</td><td>{optionalDate(driver.lastAccessAt)}</td><td>{dateTime(driver.createdAt)}</td><td>{driver.createdByDisplayName ?? "—"}</td><td><div className="admin-actions"><button type="button" onClick={() => beginEdit(driver)}>Editar</button>{driver.membershipStatus === "active" ? <button type="button" disabled={acting === driver.userId} onClick={() => void run(driver, "deactivate")}>Desactivar</button> : <button type="button" disabled={acting === driver.userId} onClick={() => void run(driver, "activate")}>Activar</button>}<button type="button" disabled={acting === driver.userId} onClick={() => void run(driver, "reset_password")}>Restablecer contraseña</button>{driver.invitationPending ? <button type="button" disabled={acting === driver.userId} onClick={() => void run(driver, "resend_invitation")}>Reenviar invitación</button> : null}<button type="button" disabled={acting === driver.userId} onClick={() => setDeleting(driver)}>Eliminar</button></div></td></tr>)}</tbody></table></div> : null}
    {form ? <form className="organization-form admin-form" onSubmit={submit} noValidate><h3>{editing ? "Editar conductor" : "Nuevo conductor"}</h3><fieldset disabled={saving}><div className="form-grid"><Field label="Nombre" required error={errors.displayName}><input value={form.displayName} onChange={(event) => update("displayName", event.target.value)} /></Field><Field label="Correo electrónico" required error={errors.email}><input type="email" value={form.email} onChange={(event) => update("email", event.target.value)} /></Field><Field label="Teléfono" error={errors.phone}><input value={form.phone} onChange={(event) => update("phone", event.target.value)} /></Field><Field label="Idioma" required error={errors.locale}><input value={form.locale} onChange={(event) => update("locale", event.target.value)} /></Field><Field label="Zona horaria" required error={errors.timezone}><input value={form.timezone} onChange={(event) => update("timezone", event.target.value)} /></Field></div></fieldset><div className="form-actions"><button className="button button-secondary" type="button" onClick={() => setForm(null)}>Cancelar</button><button className="button" type="submit" disabled={saving}>{saving ? "Guardando conductor…" : editing ? "Guardar conductor" : "Crear conductor"}</button></div></form> : null}
    {deleting ? <div className="admin-delete-confirmation" role="dialog" aria-labelledby="delete-driver-title"><h3 id="delete-driver-title">Eliminar a {deleting.displayName}</h3><p>Solo se eliminará si no tiene dependencias. Si existen, quedará desactivado conservando su historial.</p><div className="form-actions"><button className="button button-secondary" type="button" onClick={() => setDeleting(null)}>Cancelar</button><button className="button" type="button" disabled={acting === deleting.userId} onClick={() => void run(deleting, "delete")}>Confirmar eliminación</button></div></div> : null}
    {error ? <p className="form-server-error" role="alert">{error}</p> : null}{success ? <p className="success-banner" role="status">{success}</p> : null}
  </section>;
}
function Field({ label, required = false, error, children }: { label: string; required?: boolean; error?: string; children: React.ReactElement }) { return <label className="form-field"><span>{label}{required ? " *" : ""}</span>{children}{error ? <small className="field-error">{error}</small> : null}</label>; }
function message(caught: unknown): string { return caught instanceof Error ? caught.message : "No se pudo completar la acción."; }
function actionMessage(action: DriverAction): string { switch (action) { case "activate": return "Conductor activado."; case "deactivate": return "Conductor desactivado."; case "reset_password": return "Correo de restablecimiento solicitado."; case "resend_invitation": return "Invitación reenviada."; case "delete": return "Conductor eliminado."; } }
function dateTime(value: string): string { return new Intl.DateTimeFormat("es-ES", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
function optionalDate(value: string | null): string { return value ? dateTime(value) : "Nunca"; }
