import type { AdministratorAction, AdministratorIdentityErrors, AdministratorIdentityInput, OrganizationAdministrator, OrganizationAdministratorsResult } from "@albatrans/contracts";
import { normalizeAdministratorIdentity, validateAdministratorIdentity } from "@albatrans/domain";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { createOrganizationAdministrator, loadOrganizationAdministrators, runOrganizationAdministratorAction, updateOrganizationAdministrator } from "../../data/organization-admin-repository";

const empty: AdministratorIdentityInput = { email: "", displayName: "", phone: "", locale: "es", timezone: "Europe/Madrid" };
const gateway = { load: loadOrganizationAdministrators, create: createOrganizationAdministrator, update: updateOrganizationAdministrator, action: runOrganizationAdministratorAction };
type Gateway = typeof gateway;

export function OrganizationAdministratorsManager({ organizationId, api = gateway, onChanged }: { organizationId: string; api?: Gateway; onChanged: () => Promise<void> }) {
  const [result, setResult] = useState<OrganizationAdministratorsResult | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null); const [form, setForm] = useState<AdministratorIdentityInput | null>(null); const [editing, setEditing] = useState<OrganizationAdministrator | null>(null); const [errors, setErrors] = useState<AdministratorIdentityErrors>({}); const [saving, setSaving] = useState(false); const [actingUser, setActingUser] = useState<string | null>(null); const [deleting, setDeleting] = useState<OrganizationAdministrator | null>(null);
  const refresh = useCallback(async () => { setLoading(true); setError(null); try { setResult(await api.load(organizationId)); } catch (caught) { setError(message(caught)); } finally { setLoading(false); } }, [api, organizationId]);
  useEffect(() => { void refresh(); }, [refresh]);
  const limitReached = Boolean(result && (result.effectiveLimit === null || result.assignedCount >= result.effectiveLimit));
  function beginCreate() { setEditing(null); setForm(empty); setErrors({}); setError(null); setSuccess(null); }
  function beginEdit(admin: OrganizationAdministrator) { setEditing(admin); setForm({ email: admin.email, displayName: admin.displayName, phone: admin.phone, locale: admin.locale, timezone: admin.timezone }); setErrors({}); setError(null); setSuccess(null); }
  function update<K extends keyof AdministratorIdentityInput>(field: K, value: AdministratorIdentityInput[K]) { setForm((current) => current ? { ...current, [field]: value } : current); setErrors((current) => ({ ...current, [field]: undefined })); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!form) return; const normalized = normalizeAdministratorIdentity(form); const validation = validateAdministratorIdentity(normalized); if (!validation.valid) { setErrors(validation.errors); return; } setSaving(true); setError(null); setSuccess(null); try { if (editing) await api.update(organizationId, editing.userId, normalized); else await api.create(organizationId, normalized); setSuccess(editing ? "Administrador actualizado." : "Invitación enviada y administrador creado."); setForm(null); setEditing(null); await refresh(); await onChanged(); } catch (caught) { setError(message(caught)); } finally { setSaving(false); } }
  async function run(admin: OrganizationAdministrator, action: AdministratorAction) { setActingUser(admin.userId); setError(null); setSuccess(null); try { await api.action(organizationId, admin.userId, action); setSuccess(actionMessage(action)); setDeleting(null); await refresh(); await onChanged(); } catch (caught) { setError(message(caught)); } finally { setActingUser(null); } }
  return <section className="detail-section administrators-manager" aria-labelledby="administrators-title"><div className="section-heading"><div><h2 id="administrators-title">Administradores de empresa</h2><p>{result ? `${result.assignedCount} asignados · límite ${result.effectiveLimit ?? "sin configurar"}` : "Cargando límite…"}</p></div><button className="button" type="button" disabled={loading || limitReached} onClick={beginCreate}>Nuevo administrador</button></div>
    {limitReached ? <p className="commercial-notice warning">{result?.effectiveLimit === null ? "La empresa no tiene configurado un límite de administradores." : "Se ha alcanzado el límite de administradores del plan."}</p> : null}
    {loading ? <div className="list-state" aria-busy="true">Cargando administradores…</div> : null}{!loading && result?.items.length === 0 ? <p className="list-state">No hay administradores asignados.</p> : null}
    {!loading && result?.items.length ? <div className="administrators-table-wrap"><table className="administrators-table"><thead><tr><th>Administrador</th><th>Estado</th><th>Último acceso</th><th>Creación</th><th>Creado por</th><th>Acciones</th></tr></thead><tbody>{result.items.map((admin) => <tr key={admin.userId}><td data-label="Administrador"><strong>{admin.displayName}</strong><span>{admin.email}</span><small>{admin.phone || "Sin teléfono"}</small></td><td data-label="Estado"><span className={`status-badge status-${admin.membershipStatus}`}>{admin.membershipStatus}</span></td><td data-label="Último acceso">{optionalDate(admin.lastAccessAt)}</td><td data-label="Creación">{dateTime(admin.createdAt)}</td><td data-label="Creado por">{admin.createdByDisplayName ?? "—"}</td><td data-label="Acciones"><div className="admin-actions"><button type="button" onClick={() => beginEdit(admin)}>Editar</button>{admin.membershipStatus === "active" ? <button type="button" disabled={actingUser === admin.userId} onClick={() => void run(admin, "deactivate")}>Desactivar</button> : <button type="button" disabled={actingUser === admin.userId} onClick={() => void run(admin, "activate")}>Activar</button>}<button type="button" disabled={actingUser === admin.userId} onClick={() => void run(admin, "reset_password")}>Restablecer contraseña</button>{admin.membershipStatus === "invited" ? <button type="button" disabled={actingUser === admin.userId} onClick={() => void run(admin, "resend_invitation")}>Reenviar invitación</button> : null}<button type="button" disabled={actingUser === admin.userId} onClick={() => setDeleting(admin)}>Eliminar</button></div></td></tr>)}</tbody></table></div> : null}
    {form ? <form className="organization-form admin-form" onSubmit={submit} noValidate><h3>{editing ? "Editar administrador" : "Nuevo administrador"}</h3><fieldset disabled={saving}><div className="form-grid"><Field label="Nombre" required error={errors.displayName}><input value={form.displayName} onChange={(event) => update("displayName", event.target.value)} /></Field><Field label="Correo electrónico" required error={errors.email}><input type="email" value={form.email} onChange={(event) => update("email", event.target.value)} /></Field><Field label="Teléfono" error={errors.phone}><input value={form.phone} onChange={(event) => update("phone", event.target.value)} /></Field><Field label="Idioma" required error={errors.locale}><input value={form.locale} onChange={(event) => update("locale", event.target.value)} /></Field><Field label="Zona horaria" required error={errors.timezone}><input value={form.timezone} onChange={(event) => update("timezone", event.target.value)} /></Field></div></fieldset><div className="form-actions"><button className="button button-secondary" type="button" onClick={() => setForm(null)}>Cancelar</button><button className="button" type="submit" disabled={saving}>{saving ? "Guardando administrador…" : editing ? "Guardar administrador" : "Crear administrador"}</button></div></form> : null}
    {deleting ? <div className="admin-delete-confirmation" role="dialog" aria-labelledby="delete-admin-title"><h3 id="delete-admin-title">Eliminar a {deleting.displayName}</h3><p>Solo se eliminará si no tiene dependencias. Esta acción elimina su acceso y su identidad Auth.</p><div className="form-actions"><button className="button button-secondary" type="button" onClick={() => setDeleting(null)}>Cancelar</button><button className="button" type="button" disabled={actingUser === deleting.userId} onClick={() => void run(deleting, "delete")}>Confirmar eliminación</button></div></div> : null}
    {error ? <p className="form-server-error" role="alert">{error}</p> : null}{success ? <p className="success-banner" role="status">{success}</p> : null}
  </section>;
}

function Field({ label, required = false, error, children }: { label: string; required?: boolean; error?: string; children: React.ReactElement }) { return <label className="form-field"><span>{label}{required ? " *" : ""}</span>{children}{error ? <small className="field-error">{error}</small> : null}</label>; }
function message(caught: unknown): string { return caught instanceof Error ? caught.message : "No se pudo completar la acción."; }
function actionMessage(action: AdministratorAction): string { switch (action) { case "activate": return "Administrador activado."; case "deactivate": return "Administrador desactivado."; case "reset_password": return "Correo de restablecimiento solicitado."; case "resend_invitation": return "Invitación reenviada."; case "delete": return "Administrador eliminado."; } }
function dateTime(value: string): string { return new Intl.DateTimeFormat("es-ES", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
function optionalDate(value: string | null): string { return value ? dateTime(value) : "Nunca"; }
