import type { DriverAction, DriverIdentityInput, OrganizationDriver, OrganizationDriversResult } from "@albatrans/contracts";
import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { OrganizationDriversManager } from "./OrganizationDriversManager";

const invited: OrganizationDriver = { membershipId: "membership-1", userId: "user-1", organizationId: "org-1", email: "driver@alba.local", displayName: "Conductor Alba", phone: "+34123456789", locale: "es", timezone: "Europe/Madrid", profileStatus: "active", membershipStatus: "invited", accessActive: false, invitationPending: true, lastAccessAt: null, createdAt: "2026-08-01T10:00:00Z", createdByUserId: "super-1", createdByDisplayName: "Superadmin Local" };
const available: OrganizationDriversResult = { items: [invited], assignedCount: 1, effectiveLimit: 2 };
afterEach(cleanup);

describe("gestión de conductores", () => {
  it("muestra estado, invitación, acceso, fechas y creador", async () => { renderManager(); expect(await screen.findByText("Conductor Alba")).toBeInTheDocument(); const row = screen.getByText("Conductor Alba").closest("tr"); if (!row) throw new Error("No se encontró el conductor."); expect(within(row).getByText("Invitación pendiente")).toBeInTheDocument(); expect(within(row).getByText("Nunca")).toBeInTheDocument(); expect(within(row).getByText("Superadmin Local")).toBeInTheDocument(); expect(screen.getByText(/1 asignados.*límite 2/)).toBeInTheDocument(); });
  it("valida y crea sin exponer rol, contraseña ni referencia interna", async () => { const create = vi.fn(async () => ({ userId: "new" })); renderManager({ create }); await screen.findByText("Conductor Alba"); fireEvent.click(screen.getByRole("button", { name: "Nuevo conductor" })); expect(screen.queryByLabelText(/rol|contraseña|referencia|número interno/i)).not.toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Crear conductor" })); expect(await screen.findByText("Introduce un correo electrónico válido.")).toBeInTheDocument(); fireEvent.change(screen.getByLabelText(/Nombre/), { target: { value: " Nuevo Driver " } }); fireEvent.change(screen.getByLabelText(/Correo electrónico/), { target: { value: " DRIVER2@ALBA.LOCAL " } }); fireEvent.click(screen.getByRole("button", { name: "Crear conductor" })); await waitFor(() => expect(create).toHaveBeenCalledWith("org-1", { email: "driver2@alba.local", displayName: "Nuevo Driver", phone: "", locale: "es", timezone: "Europe/Madrid" })); });
  it("edita y ofrece las acciones de una invitación", async () => { const update = vi.fn(async () => ({ userId: "user-1" })); const action = vi.fn(async (...args: [string, string, DriverAction]) => ({ userId: args[1] })); renderManager({ update, action }); await screen.findByText("Conductor Alba"); fireEvent.click(screen.getByRole("button", { name: "Editar" })); fireEvent.change(screen.getByLabelText(/Nombre/), { target: { value: "Conductor Actualizado" } }); fireEvent.click(screen.getByRole("button", { name: "Guardar conductor" })); await waitFor(() => expect(update).toHaveBeenCalled()); fireEvent.click(screen.getByRole("button", { name: "Reenviar invitación" })); await waitFor(() => expect(action).toHaveBeenCalledWith("org-1", "user-1", "resend_invitation")); fireEvent.click(screen.getByRole("button", { name: "Eliminar" })); fireEvent.click(within(screen.getByRole("dialog")).getByRole("button", { name: "Confirmar eliminación" })); await waitFor(() => expect(action).toHaveBeenCalledWith("org-1", "user-1", "delete")); });
  it("bloquea la creación al alcanzar max_drivers", async () => { renderManager({ result: { ...available, assignedCount: 2 } }); expect(await screen.findByText("Se ha alcanzado el límite de conductores del plan.")).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Nuevo conductor" })).toBeDisabled(); });
});

function renderManager(options: { result?: OrganizationDriversResult; create?: (organizationId: string, input: DriverIdentityInput) => Promise<{ userId: string }>; update?: (organizationId: string, userId: string, input: DriverIdentityInput) => Promise<{ userId: string }>; action?: (organizationId: string, userId: string, action: DriverAction) => Promise<{ userId: string }> } = {}) { const api = { load: vi.fn(async () => options.result ?? available), create: options.create ?? vi.fn(async () => ({ userId: "new" })), update: options.update ?? vi.fn(async () => ({ userId: "user-1" })), action: options.action ?? vi.fn(async () => ({ userId: "user-1" })) }; return render(<OrganizationDriversManager organizationId="org-1" api={api} onChanged={async () => undefined} />); }
