import type { ChangeOrganizationModuleInput, ChangeOrganizationModuleResult, ModuleOverrideMode, OrganizationDetailModule } from "@albatrans/contracts";
import { useMemo, useState } from "react";
import { changeOrganizationModule } from "../../data/organization-command-repository";

type Changer = (organizationId: string, input: ChangeOrganizationModuleInput) => Promise<ChangeOrganizationModuleResult>;

export function OrganizationModulesManager({ organizationId, modules, changer = changeOrganizationModule, onChanged }: { organizationId: string; modules: readonly OrganizationDetailModule[]; changer?: Changer; onChanged: () => Promise<void> }) {
  const [category, setCategory] = useState("all"); const [effective, setEffective] = useState("all");
  const [editing, setEditing] = useState<OrganizationDetailModule | null>(null); const [mode, setMode] = useState<ModuleOverrideMode>("inherit"); const [reason, setReason] = useState(""); const [confirmed, setConfirmed] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null);
  const categories = useMemo(() => [...new Set(modules.map((module) => module.category))].sort(), [modules]);
  const visible = modules.filter((module) => (category === "all" || module.category === category) && (effective === "all" || (effective === "enabled") === module.enabled));
  const activeCount = modules.filter((module) => module.enabled).length;
  function edit(module: OrganizationDetailModule) { setEditing(module); setMode(module.overrideMode ?? "inherit"); setReason(""); setConfirmed(false); setError(null); setSuccess(null); }
  async function save() {
    if (!editing) return;
    if (mode !== "inherit" && !reason.trim()) { setError("El motivo es obligatorio para activar o desactivar."); return; }
    if (!confirmed) { setError("Confirma el cambio antes de guardar."); return; }
    setSaving(true); setError(null); setSuccess(null);
    try { await changer(organizationId, { moduleCode: editing.code, overrideMode: mode, reason: reason.trim() }); await onChanged(); setSuccess(`${editing.name} actualizado correctamente.`); setEditing(null); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo cambiar el módulo."); }
    finally { setSaving(false); }
  }
  return <section className="detail-section modules-manager" aria-labelledby="modules-manager-title"><div className="section-heading"><div><h2 id="modules-manager-title">Módulos</h2><p>{activeCount} de {modules.length} módulos activos</p></div><div className="module-filters"><label>Categoría <select value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">Todas</option>{categories.map((value) => <option key={value}>{value}</option>)}</select></label><label>Estado efectivo <select value={effective} onChange={(event) => setEffective(event.target.value)}><option value="all">Todos</option><option value="enabled">Activos</option><option value="disabled">Inactivos</option></select></label></div></div>
    {visible.length === 0 ? <p className="list-state">No hay módulos para estos filtros.</p> : <div className="modules-table-wrap"><table className="modules-table"><thead><tr><th>Módulo</th><th>Categoría</th><th>Plan</th><th>Override</th><th>Efectivo</th><th>Motivo y cambio</th><th>Acción</th></tr></thead><tbody>{visible.map((module) => <tr key={module.code}><td data-label="Módulo"><strong>{module.name}</strong><code>{module.code}</code>{module.code === "api_access" ? <small className="technical-badge">Módulo técnico</small> : null}</td><td data-label="Categoría">{module.category}</td><td data-label="Plan">{module.planIncluded ? "Incluido" : "No incluido"}</td><td data-label="Override">{overrideLabel(module)}</td><td data-label="Efectivo"><span className={`module-effective ${module.enabled ? "enabled" : "disabled"}`}>{module.enabled ? "Activo" : "Inactivo"}</span></td><td data-label="Motivo y cambio"><span>{module.overrideReason ?? "—"}</span><small>{module.changedAt ? `${dateTime(module.changedAt)} · ${module.changedByDisplayName ?? module.changedBy ?? "Usuario"}` : "Sin override previo"}</small></td><td data-label="Acción"><button className="button button-secondary" type="button" onClick={() => edit(module)}>Configurar</button></td></tr>)}</tbody></table></div>}
    {editing ? <div className="module-confirmation" role="dialog" aria-labelledby="module-confirmation-title"><h3 id="module-confirmation-title">Configurar {editing.name}</h3><p>Plan: <strong>{editing.planIncluded ? "incluido" : "no incluido"}</strong>. Estado efectivo actual: <strong>{editing.enabled ? "activo" : "inactivo"}</strong>.</p><label className="form-field"><span>Comportamiento</span><select value={mode} onChange={(event) => { setMode(overrideMode(event.target.value)); setConfirmed(false); setError(null); }}><option value="inherit">Heredar del plan</option><option value="enabled">Activar manualmente</option><option value="disabled">Desactivar manualmente</option></select></label><label className="form-field"><span>Motivo{mode === "inherit" ? " (opcional)" : " *"}</span><textarea rows={3} value={reason} onChange={(event) => setReason(event.target.value)} /></label><label className="checkbox-field"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} /> Confirmo que este cambio no elimina datos históricos del módulo.</label><div className="form-actions"><button className="button button-secondary" type="button" disabled={saving} onClick={() => setEditing(null)}>Cancelar</button><button className="button" type="button" disabled={saving || !confirmed || (mode !== "inherit" && !reason.trim())} onClick={() => void save()}>{saving ? "Guardando módulo…" : "Guardar módulo"}</button></div></div> : null}
    {error ? <p className="form-server-error" role="alert">{error}</p> : null}{success ? <p className="success-banner" role="status">{success}</p> : null}
  </section>;
}

function overrideLabel(module: OrganizationDetailModule): string { if (module.overrideMode === "enabled") return "Activado por override"; if (module.overrideMode === "disabled") return "Desactivado por override"; return module.planIncluded ? "Heredado · incluido por plan" : "Heredado · fuera del plan"; }
function overrideMode(value: string): ModuleOverrideMode { return value === "enabled" ? "enabled" : value === "disabled" ? "disabled" : "inherit"; }
function dateTime(value: string): string { return new Intl.DateTimeFormat("es-ES", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
