import type { ChangeOrganizationLimitInput, ChangeOrganizationLimitResult, OrganizationDetailLimit, OrganizationLimitAction } from "@albatrans/contracts";
import { validateCustomLimitValue } from "@albatrans/domain";
import { useState } from "react";
import { changeOrganizationLimit } from "../../data/organization-command-repository";

type Changer = (organizationId: string, input: ChangeOrganizationLimitInput) => Promise<ChangeOrganizationLimitResult>;
export function OrganizationLimitsManager({ organizationId, limits, changer = changeOrganizationLimit, onChanged }: { organizationId: string; limits: readonly OrganizationDetailLimit[]; changer?: Changer; onChanged: () => Promise<void> }) {
  const [editing, setEditing] = useState<OrganizationDetailLimit | null>(null); const [action, setAction] = useState<OrganizationLimitAction>("inherit"); const [value, setValue] = useState(""); const [reason, setReason] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null);
  function edit(limit: OrganizationDetailLimit) { setEditing(limit); setAction(limit.overrideMode === "custom" ? "custom" : "inherit"); setValue(limit.overrideValue?.toString() ?? ""); setReason(""); setError(null); setSuccess(null); }
  async function save() { if (!editing) return; let numberValue: number | null = null; if (action === "custom") { if (value.trim() === "") { setError("Introduce un valor personalizado."); return; } const parsedValue = Number(value); const validation = validateCustomLimitValue(parsedValue); if (validation) { setError(validation); return; } if (!reason.trim()) { setError("El motivo es obligatorio para un límite personalizado."); return; } numberValue = parsedValue; } if (action !== "custom" && editing.planValue === null) { setError("El plan no define este límite. Debes establecer un valor personalizado."); return; } setSaving(true); setError(null); setSuccess(null); try { await changer(organizationId, { limitCode: editing.code, action, value: numberValue, reason: reason.trim() }); await onChanged(); setSuccess(`${editing.name} actualizado correctamente.`); setEditing(null); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo cambiar el límite."); } finally { setSaving(false); } }
  return <section className="detail-section limits-manager" aria-labelledby="limits-title"><div className="section-heading"><div><h2 id="limits-title">Límites</h2><p>Valores efectivos heredados del plan o personalizados por empresa.</p></div></div>
    {limits.length === 0 ? <p className="list-state">No hay límites disponibles.</p> : <div className="modules-table-wrap"><table className="modules-table"><thead><tr><th>Límite</th><th>Plan</th><th>Override</th><th>Efectivo</th><th>Consumo</th><th>Utilización</th><th>Acción</th></tr></thead><tbody>{limits.map((limit) => <tr key={limit.code}><td><strong>{limit.name}</strong><code>{limit.code}</code></td><td>{format(limit.planValue, limit.unit)}</td><td>{limit.overrideMode === "custom" ? format(limit.overrideValue, limit.unit) : limit.overrideMode === "inherit" ? "Herencia explícita" : "Sin override"}</td><td><strong>{format(limit.limit, limit.unit)}</strong></td><td>{format(limit.usage, limit.unit)}</td><td>{limit.percentage === null ? "Sin configurar" : <><span>{limit.percentage}%</span><progress max="100" value={Math.min(limit.percentage, 100)} /></>}</td><td><button className="button button-secondary" type="button" onClick={() => edit(limit)}>Configurar</button></td></tr>)}</tbody></table></div>}
    {editing ? <div className="module-confirmation" role="dialog" aria-labelledby="limit-dialog-title"><h3 id="limit-dialog-title">Configurar {editing.name}</h3><p>Plan: <strong>{format(editing.planValue, editing.unit)}</strong>. Consumo: <strong>{format(editing.usage, editing.unit)}</strong>.</p><label className="form-field"><span>Comportamiento</span><select value={action} onChange={(event) => { setAction(parseAction(event.target.value)); setError(null); }}><option value="inherit" disabled={editing.planValue === null}>Heredar del plan</option><option value="custom">Valor personalizado</option><option value="delete" disabled={editing.planValue === null}>Eliminar override</option></select></label>{action === "custom" ? <><label className="form-field"><span>Valor personalizado</span><input type="number" min="0" step="1" value={value} onChange={(event) => setValue(event.target.value)} /></label><label className="form-field"><span>Motivo *</span><textarea rows={3} value={reason} onChange={(event) => setReason(event.target.value)} /></label></> : null}<div className="form-actions"><button className="button button-secondary" type="button" disabled={saving} onClick={() => setEditing(null)}>Cancelar</button><button className="button" type="button" disabled={saving} onClick={() => void save()}>{saving ? "Guardando límite…" : "Guardar límite"}</button></div></div> : null}
    {error ? <p className="form-server-error" role="alert">{error}</p> : null}{success ? <p className="success-banner" role="status">{success}</p> : null}
  </section>;
}
function parseAction(value: string): OrganizationLimitAction { return value === "custom" ? "custom" : value === "delete" ? "delete" : "inherit"; }
function format(value: number | null, unit: OrganizationDetailLimit["unit"]): string { if (value === null) return "Sin configurar"; if (unit === "bytes") return new Intl.NumberFormat("es-ES", { style: "unit", unit: "gigabyte", maximumFractionDigits: 2 }).format(value / 1_073_741_824); return new Intl.NumberFormat("es-ES").format(value); }
