import type { LimitCode, LimitUnit, ModuleCode, ModuleOverrideMode } from "./entitlements";
import type { Organization, OrganizationSubscription, PaymentStatus, PlanCode, SubscriptionStatus } from "./organizations";

export interface OrganizationDetailSubscription { planId: string; planCode: PlanCode; planName: string; status: SubscriptionStatus; paymentStatus: PaymentStatus; startsAt: string; periodStartsAt: string | null; periodEndsAt: string | null; paidThrough: string | null; gracePeriodEndsAt: string | null; cancelAtPeriodEnd: boolean; notes: string | null; raw: OrganizationSubscription; }
export interface OrganizationDetailLimit { code: LimitCode; name: string; unit: LimitUnit; planValue: number | null; overrideMode: "inherit" | "custom" | null; overrideValue: number | null; usage: number; limit: number | null; percentage: number | null; source: "plan" | "organization_override" | "unconfigured"; }
export interface OrganizationDetailModule { code: ModuleCode; name: string; category: string; planIncluded: boolean; enabled: boolean; source: "plan" | "override_enabled" | "override_disabled" | "not_in_plan"; overrideMode: ModuleOverrideMode | null; overrideReason: string | null; changedAt: string | null; changedBy: string | null; changedByDisplayName: string | null; }
export interface OrganizationDetailMember { id: string; userId: string; displayName: string; role: "admin_empresa" | "conductor"; joinedAt: string | null; }
export interface OrganizationDetailAudit { id: string; action: string; actorScope: "platform" | "organization" | "system"; reason: string | null; occurredAt: string; entityType: string; }
export interface OrganizationDetail { organization: Organization; subscription: OrganizationDetailSubscription | null; limits: readonly OrganizationDetailLimit[]; modules: readonly OrganizationDetailModule[]; activeAdminCount: number; activeDriverCount: number; members: readonly OrganizationDetailMember[]; audit: readonly OrganizationDetailAudit[]; }
