export const regulatoryDocumentTypes = ["control_document", "ecmr_draft"] as const;
export type RegulatoryDocumentType = typeof regulatoryDocumentTypes[number];
export const regulatoryDocumentStatuses = ["draft", "ready", "issued", "in_execution", "completed", "amended", "cancelled", "archived"] as const;
export type RegulatoryDocumentStatus = typeof regulatoryDocumentStatuses[number];
export type RegulatoryPartyRole = "carrier" | "consignor" | "consignee" | "shipper" | "sender" | "receiver" | "subcontractor" | "other";
export interface RegulatoryPartySnapshot { role: RegulatoryPartyRole; legalName: string | null; taxId: string | null; address: string | null; contactName: string | null; email: string | null; phone: string | null; }
export interface RegulatoryStopSnapshot { id: string; sequence: number; type: string; locationName: string | null; address: string | null; city: string | null; plannedAt: string | null; actualAt: string | null; contact: string | null; instructions: string | null; observations: string | null; }
export interface RegulatoryGoodsSnapshot { id: string; description: string | null; quantity: number | null; unit: string | null; packages: number | null; pallets: number | null; grossWeightKg: number | null; volumeM3: number | null; reference: string | null; marks: string | null; observations: string | null; specialRequirements: Record<string, unknown> | null; }
export interface RegulatoryTransportSnapshot { orderId: string; reference: string; serviceType: string | null; plannedPickupAt: string | null; plannedDeliveryAt: string | null; vehiclePlate: string | null; trailerPlate: string | null; driverName: string | null; }
export interface RegulatoryDocumentSnapshotV1 extends Record<string, unknown> { schemaVersion: "1.0"; documentType: RegulatoryDocumentType; capturedAt: string; parties: RegulatoryPartySnapshot[]; transport: RegulatoryTransportSnapshot; stops: RegulatoryStopSnapshot[]; goods: RegulatoryGoodsSnapshot[]; observations: string | null; }
export interface RegulatoryValidationIssue { code: string; path: string; message: string; severity: "error" | "warning"; }
export interface RegulatoryValidationResult { errors: RegulatoryValidationIssue[]; warnings: RegulatoryValidationIssue[]; complete: boolean; }
export interface RegulatoryRevision { id: string; revisionNumber: number; snapshot: RegulatoryDocumentSnapshotV1; contentHash: string | null; reason: string | null; previousRevisionId: string | null; createdAt: string; }
export interface RegulatoryDocument { id: string; organizationId: string; transportOrderId: string; documentId: string | null; documentType: RegulatoryDocumentType; schemaVersion: string; documentNumber: string | null; status: RegulatoryDocumentStatus; revisionNumber: number; effectiveAt: string | null; issuedAt: string | null; closedAt: string | null; cancelledAt: string | null; currentSnapshot: RegulatoryDocumentSnapshotV1; contentHash: string | null; externalDocumentId: string | null; externalProvider: string | null; externalStatus: string | null; createdAt: string; updatedAt: string; }
export interface RegulatoryEvidence { id: string; evidenceType: "signature" | "pod" | "photo" | "timestamp" | "document" | "note" | "incident"; documentVersionId: string | null; signatureId: string | null; payload: Record<string, unknown>; createdAt: string; }
export interface RegulatoryDocumentExportV1 { format: "albatrans.regulatory.v1"; header: { documentId: string; documentType: RegulatoryDocumentType; documentNumber: string | null; revision: number; schemaVersion: string; status: RegulatoryDocumentStatus; contentHash: string | null; }; parties: RegulatoryPartySnapshot[]; transport: RegulatoryTransportSnapshot; stops: RegulatoryStopSnapshot[]; goods: RegulatoryGoodsSnapshot[]; signatures: Array<{ signerName: string; signerRole: string | null; signedAt: string; type: string; hash: string; }>; evidences: RegulatoryEvidence[]; revisions: Array<{ revision: number; hash: string | null; reason: string | null; createdAt: string; }>; }
export type RegulatoryAction = "create_draft" | "validate" | "issue" | "create_revision" | "sign" | "complete" | "cancel" | "archive" | "generate_pdf" | "download_pdf" | "export";
export interface RegulatoryCommand { action: RegulatoryAction; organizationId: string; transportOrderId?: string; regulatoryDocumentId?: string; documentType?: RegulatoryDocumentType; reason?: string; values?: Record<string, unknown>; idempotencyKey: string; }
