import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { InvoicesPanel } from "./InvoicesPanel";

const repository=vi.hoisted(()=>({loadInvoiceWorkspace:vi.fn(),loadInvoiceDetail:vi.fn(),configureInvoiceFiscal:vi.fn(),issueInvoice:vi.fn(),recordInvoicePayment:vi.fn(),cancelInvoice:vi.fn(),createCorrectiveInvoice:vi.fn(),generateInvoicePdf:vi.fn(),downloadInvoicePdf:vi.fn()}));
vi.mock("../../data/billing-repository",()=>repository);
const invoice={id:"inv-1",organization_id:"org-1",invoice_series_id:"series-1",invoice_number:"F-2026-000001",issue_date:"2026-08-13",service_period_start:null,service_period_end:null,customer_id:"client-1",status:"issued",currency_code:"EUR",subtotal:346.5,tax_total:72.77,total:419.27,amount_paid:0,amount_due:419.27,due_date:"2026-09-12",payment_terms_days:30,notes:null,preinvoice_id:"pre-1",created_by:"user",created_at:"2026-08-13",issued_by:"user",issued_at:"2026-08-13",cancelled_by:null,cancelled_at:null,cancellation_reason:null,rectified_invoice_id:null,fiscal_snapshot_json:{issuer:{legalName:"Demo Fase H",taxId:"B123"},customer:{legalName:"Cliente Demo",taxId:"A123"}},billing_snapshot_json:{},correlation_id:"c",idempotency_key:"k",customerName:"Cliente Demo"};
const workspace={settings:{organization_id:"org-1",legal_name:"Demo Fase H",tax_id:"B123",address_line_1:"Calle 1",address_line_2:null,postal_code:"28001",city:"Madrid",region:null,country_code:"ES",billing_email:null,default_payment_terms_days:30,updated_by:"user",created_at:"",updated_at:""},series:[{id:"series-1",organization_id:"org-1",code:"F",name:"Principal",prefix:"F",next_number:2,active:true,is_primary:true,fiscal_year_mode:"calendar_year",created_by:"user",created_at:"",updated_at:""}],taxes:[{id:"tax-1",organization_id:"org-1",code:"IVA21",name:"IVA 21 %",kind:"standard",rate:21,exemption_reason:null,active:true,created_by:"user",created_at:"",updated_at:""}],invoices:[invoice]};
const detail={invoice,lines:[{id:"line-1",description:"Servicio PRE-2026-0001",subtotal:346.5,tax_rate:21,tax_amount:72.77,total:419.27}],payments:[],documents:[],audit:[{id:"audit-1",action:"billing.invoice_issued",created_at:"2026-08-13",reason:null}]};

describe("InvoicesPanel",()=>{beforeEach(()=>{vi.clearAllMocks();repository.loadInvoiceWorkspace.mockResolvedValue(workspace);repository.loadInvoiceDetail.mockResolvedValue(detail);repository.issueInvoice.mockResolvedValue({});repository.recordInvoicePayment.mockResolvedValue({});repository.generateInvoicePdf.mockResolvedValue({});});afterEach(cleanup);
 it("lista importes y estados fiscales",async()=>{render(<InvoicesPanel organizationId="org-1" preinvoices={[]}/>);expect(await screen.findByRole("button",{name:"F-2026-000001"})).toBeInTheDocument();expect(screen.getAllByText(/419,27/)).toHaveLength(2);expect(screen.getByText("issued")).toBeInTheDocument();});
 it("muestra snapshot, lineas y auditoria en detalle",async()=>{render(<InvoicesPanel organizationId="org-1" preinvoices={[]}/>);fireEvent.click(await screen.findByText("F-2026-000001"));expect(await screen.findByText(/Emisor: Demo Fase H/)).toBeInTheDocument();expect(screen.getByText("Servicio PRE-2026-0001")).toBeInTheDocument();expect(screen.getByText(/billing.invoice_issued/)).toBeInTheDocument();});
 it("registra un cobro manual",async()=>{render(<InvoicesPanel organizationId="org-1" preinvoices={[]}/>);fireEvent.click(await screen.findByRole("button",{name:"F-2026-000001"}));await screen.findByText("Registrar cobro");fireEvent.change(screen.getByLabelText("Importe"),{target:{value:"200"}});fireEvent.click(screen.getByText("Registrar cobro"));await waitFor(()=>expect(repository.recordInvoicePayment).toHaveBeenCalledWith(expect.objectContaining({amount:"200",invoiceId:"inv-1"})));});
 it("solicita PDF privado",async()=>{render(<InvoicesPanel organizationId="org-1" preinvoices={[]}/>);fireEvent.click(await screen.findByRole("button",{name:"F-2026-000001"}));fireEvent.click(await screen.findByText("Generar PDF"));await waitFor(()=>expect(repository.generateInvoicePdf).toHaveBeenCalledWith(expect.objectContaining({invoiceId:"inv-1"})));});
});
