import { validateDocumentFile } from "@albatrans/domain";
import { type FormEvent, useCallback, useEffect, useState } from "react";
import { downloadDocument, executeDocumentCommand, loadDocuments, uploadDocument, type DocumentListItem } from "../../data/documents-repository";

export function DocumentManager({ organizationId, orderId, stops }: { organizationId: string; orderId: string; stops: { id: string; position: number; stop_type: string }[] }) {
  const [documents, setDocuments] = useState<DocumentListItem[]>([]), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState(""), [success, setSuccess] = useState("");
  const refresh = useCallback(async () => { setLoading(true); try { setDocuments(await loadDocuments({ organizationId, transportOrderId: orderId })); setError(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudieron cargar los documentos."); } finally { setLoading(false); } }, [organizationId, orderId]);
  useEffect(() => { void refresh(); }, [refresh]);
  async function upload(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget), cameraFile = data.get("cameraFile"), selectedFile = data.get("file"), file = cameraFile instanceof File && cameraFile.size > 0 ? cameraFile : selectedFile;
    if (!(file instanceof File) || file.size === 0) { setError("Selecciona un archivo."); return; }
    try { setBusy(true); setError(""); setSuccess(""); const validated = validateDocumentFile(file.type, file.size); await uploadDocument({ organizationId, documentType: String(data.get("documentType")), title: String(data.get("title")), description: String(data.get("description") || "") || undefined, source: cameraFile instanceof File && cameraFile.size > 0 ? "camera" : "upload", originalFilename: file.name, mimeType: validated.mimeType, sizeBytes: validated.sizeBytes, relations: { transportOrderId: orderId, transportStopId: String(data.get("stopId") || "") || undefined } }, file); event.currentTarget.reset(); setSuccess("Documento confirmado y disponible."); await refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo subir el documento. Puedes reintentarlo."); } finally { setBusy(false); }
  }
  async function command(action: "archive" | "create_pod" | "confirm_pod" | "reject_pod" | "create_signature" | "revoke_signature", documentId: string | undefined, values: Record<string, string | null> = {}, entityId?: string, versionId?: string) {
    try { setBusy(true); setError(""); await executeDocumentCommand({ action, organizationId, documentId, entityId, versionId, transportOrderId: orderId, values, reason: action === "archive" ? values.reason ?? "Archivado administrativo" : undefined }); setSuccess("Operación documental completada."); await refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo completar la operación."); } finally { setBusy(false); }
  }
  async function open(versionId: string) { try { const result = await downloadDocument(organizationId, versionId); window.open(result.signedUrl, "_blank", "noopener,noreferrer"); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo abrir el documento."); } }
  return <section className="detail-section document-manager" aria-labelledby="documents-title">
    <div className="section-heading"><div><h2 id="documents-title">Documentos y POD</h2><p>Archivos privados. Las firmas dibujadas o tipadas no se presentan como firma electrónica cualificada.</p></div></div>
    {error && <p role="alert" className="error-banner">{error}</p>}{success && <p role="status" className="success-banner">{success}</p>}
    <form className="panel master-data-form" onSubmit={upload} aria-label="Subir documento">
      <div className="form-grid"><label>Título<input name="title" required maxLength={200} /></label><label>Tipo documental<input name="documentType" required maxLength={100} placeholder="albarán, fotografía, justificante…" /></label><label>Parada opcional<select name="stopId"><option value="">Toda la orden</option>{stops.map((stop) => <option key={stop.id} value={stop.id}>Parada {stop.position} · {stop.stop_type}</option>)}</select></label><label className="full-field">Descripción<textarea name="description" maxLength={1000} /></label><label>Archivo<input name="file" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" /></label><label>Captura con cámara<input name="cameraFile" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" aria-describedby="camera-help" /></label></div>
      <p id="camera-help" className="field-hint">JPEG, PNG, WebP o PDF. Máximo 10 MiB.</p><button className="button" disabled={busy}>{busy ? "Subiendo y confirmando…" : "Subir documento"}</button>
    </form>
    {loading ? <p role="status" aria-busy="true">Cargando documentos…</p> : documents.length === 0 ? <p>Sin documentos asociados.</p> : <div className="document-grid">{documents.map((document) => <article className="panel document-card" key={document.id}><header><div><h3>{document.title}</h3><p><code>{document.document_type}</code> · {document.status}</p></div>{document.status !== "archived" && <button className="button button-secondary" disabled={busy} onClick={() => void command("archive", document.id, { reason: "Archivado administrativo" })}>Archivar</button>}</header><p>{document.description || "Sin descripción."}</p><h4>Versiones</h4><ul>{document.versions.map((version) => <li key={version.id}><span>v{version.version_number} · {version.mime_type} · {Math.ceil(version.size_bytes / 1024)} KiB · {version.status}</span>{version.status === "available" && <button className="link-button" onClick={() => void open(version.id)}>Vista previa / descarga segura</button>}</li>)}</ul>{document.status === "available" && document.proofs.length === 0 && <button className="button button-secondary" disabled={busy} onClick={() => void command("create_pod", document.id, { deliveredAt: new Date().toISOString() })}>Crear POD</button>}{document.proofs.map((pod) => <div className="document-subsection" key={pod.id}><strong>POD · {pod.status}</strong>{pod.status === "captured" && <div className="inline-actions"><button className="button button-secondary" disabled={busy} onClick={() => void command("confirm_pod", document.id, {}, pod.id)}>Confirmar</button><button className="button button-secondary" disabled={busy} onClick={() => void command("reject_pod", document.id, {}, pod.id)}>Rechazar</button></div>}</div>)}{document.status === "available" && <SignatureForm busy={busy} submit={(values) => command("create_signature", document.id, values, undefined, document.current_version_id ?? undefined)} />}{document.signatures.length > 0 && <ul aria-label="Firmas">{document.signatures.map((signature) => <li key={signature.id}>{signature.signature_type} · {signature.signer_name} · {signature.revoked_at ? "revocada" : "vigente"}{!signature.revoked_at && <button className="link-button" disabled={busy} onClick={() => void command("revoke_signature", document.id, { reason: "Revocación administrativa" }, signature.id)}>Revocar</button>}</li>)}</ul>}</article>)}</div>}
  </section>;
}
function SignatureForm({ busy, submit }: { busy: boolean; submit: (values: Record<string, string | null>) => Promise<void> }) { const [name, setName] = useState(""), [signature, setSignature] = useState(""); return <form className="document-subsection" onSubmit={(event) => { event.preventDefault(); void submit({ signatureType: "typed", signerName: name, signatureValue: signature, signedAt: new Date().toISOString() }).then(() => { setName(""); setSignature(""); }); }}><h4>Firma tipada básica</h4><label>Firmante<input value={name} onChange={(event) => setName(event.target.value)} required /></label><label>Representación de firma<input value={signature} onChange={(event) => setSignature(event.target.value)} required /></label><button className="button button-secondary" disabled={busy}>Registrar firma</button></form>; }
