import {cleanup,fireEvent,render,screen,waitFor} from "@testing-library/react";
import {MemoryRouter} from "react-router-dom";
import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import {TransportOrderDetailPage} from "./TransportOrderDetailPage";
const repository=vi.hoisted(()=>({loadTransportDetail:vi.fn(),loadTransportOptions:vi.fn(),transportCommand:vi.fn()}));vi.mock("../../data/transport-repository",()=>repository);
const documents=vi.hoisted(()=>({loadDocuments:vi.fn(),uploadDocument:vi.fn(),downloadDocument:vi.fn(),executeDocumentCommand:vi.fn()}));vi.mock("../../data/documents-repository",()=>documents);
const billing=vi.hoisted(()=>({loadTransportBillingView:vi.fn(),loadBillingSupplementDefinitions:vi.fn(),calculateOrderBilling:vi.fn(),validateOrderBilling:vi.fn(),reopenOrderBilling:vi.fn(),addOrderSupplement:vi.fn(),addOrderAdjustment:vi.fn()}));vi.mock("../billing/../..//data/billing-repository",()=>billing);vi.mock("../../data/billing-repository",()=>billing);
beforeEach(()=>{documents.loadDocuments.mockResolvedValue([]);repository.loadTransportDetail.mockResolvedValue({order:{id:"order-1",organization_id:"org-1",order_number:"TR-00000001",customer_id:"client-1",status:"draft",economic_status:"unpriced",billable_km:null,current_valuation_id:null,priority:"normal",transport_type:"General",planned_pickup_at:null,planned_delivery_at:null,requested_pickup_at:null,requested_delivery_at:null,assigned_driver_id:null,assigned_vehicle_id:null,notes:null,created_by:"user-1",created_at:"2026-01-01T00:00:00Z",updated_at:"2026-01-01T00:00:00Z",archived_at:null},customerName:"Cliente Uno",stops:[],items:[],assignments:[],events:[{id:"event-1",organization_id:"org-1",transport_order_id:"order-1",event_type:"transport.created",actor_user_id:"user-1",entity_type:"order",entity_id:"order-1",payload:{},occurred_at:"2026-01-01T00:00:00Z",correlation_id:"correlation-1"}]});repository.loadTransportOptions.mockResolvedValue([]);repository.transportCommand.mockResolvedValue({organizationId:"org-1",orderId:"order-1",entityId:"order-1",action:"transition",eventType:"transport.cancelled"});billing.loadTransportBillingView.mockResolvedValue({order:{id:"order-1",customer_id:"client-1",transport_type:"General",billable_km:null,economic_status:"unpriced",current_valuation_id:null},customerName:"Cliente Uno",valuation:null,supplements:[],adjustments:[],activePreinvoice:null});billing.loadBillingSupplementDefinitions.mockResolvedValue([]);billing.calculateOrderBilling.mockResolvedValue({ok:true});billing.validateOrderBilling.mockResolvedValue({ok:true});billing.reopenOrderBilling.mockResolvedValue({ok:true});billing.addOrderSupplement.mockResolvedValue({ok:true});billing.addOrderAdjustment.mockResolvedValue({ok:true});});afterEach(()=>{cleanup();vi.clearAllMocks();});
describe("detalle de orden",()=>{it("muestra stops, items, asignaciones y timeline",async()=>{render(<MemoryRouter><TransportOrderDetailPage organizationId="org-1" orderId="order-1" platform={false}/></MemoryRouter>);expect(await screen.findByRole("heading",{name:"Cliente Uno"})).toBeInTheDocument();expect(screen.getByRole("heading",{name:"Paradas"})).toBeInTheDocument();expect(screen.getByRole("heading",{name:"Mercancías"})).toBeInTheDocument();expect(screen.getByRole("heading",{name:"Asignaciones"})).toBeInTheDocument();expect(screen.getByText("transport.created")).toBeInTheDocument();});it("solo ofrece transiciones válidas",async()=>{render(<MemoryRouter><TransportOrderDetailPage organizationId="org-1" orderId="order-1" platform={false}/></MemoryRouter>);await screen.findByText("transport.created");expect(screen.getByRole("button",{name:"planned"})).toBeInTheDocument();expect(screen.queryByRole("button",{name:"completed"})).not.toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"cancelled"}));await waitFor(()=>expect(repository.transportCommand).toHaveBeenCalledWith(expect.objectContaining({targetStatus:"cancelled"})));});});
