import type { ClientInvoiceListItem, ClientTransportListItem } from "@albatrans/contracts";
import { useEffect, useState } from "react";
import { Link, NavLink, useParams } from "react-router-dom";
import { useAuth } from "../../auth/AuthContext";
import { createClientSignedUrl, listClientDocuments, listClientInvoices, listClientTransports, loadClientPortalProfile, loadClientTransport, type ClientDocumentItem, type ClientPortalProfileData, type ClientTransportDetail } from "../../data/client-portal-repository";

export function ClientPortalLayout(){
 const {signOut}=useAuth();
 return <div className="client-shell"><header className="client-header"><Link to="/client" className="client-brand">Albatrans · Portal cliente</Link><nav aria-label="Portal cliente"><NavLink to="/client/transports">Transportes</NavLink><NavLink to="/client/documents">Documentos</NavLink><NavLink to="/client/invoices">Facturas</NavLink><NavLink to="/client/profile">Perfil</NavLink></nav><button className="button button-secondary" onClick={signOut}>Salir</button></header></div>;
}

function Frame({children}:{children:React.ReactNode}){return <><ClientPortalLayout/><main className="client-main">{children}</main></>}
function State({text}:{text:string}){return <p className="list-state" role="status">{text}</p>}

export function ClientDashboard(){const [profile,setProfile]=useState<ClientPortalProfileData|null>(null);const [orders,setOrders]=useState<ClientTransportListItem[]>([]);const [invoices,setInvoices]=useState<ClientInvoiceListItem[]>([]);const [error,setError]=useState("");useEffect(()=>{void Promise.all([loadClientPortalProfile(),listClientTransports(),listClientInvoices()]).then(([p,o,i])=>{setProfile(p);setOrders(o);setInvoices(i)}).catch(e=>setError(e instanceof Error?e.message:"Error"))},[]);return <Frame>{error?<State text={error}/>:!profile?<State text="Cargando portal…"/>:<><span className="eyebrow">Portal de {profile.organizationName}</span><h1>Hola, {profile.customerName}</h1><p>Consulta el estado de tus servicios y documentación autorizada.</p><section className="client-stats" aria-label="Resumen"><article><strong>{orders.filter(x=>!["completed","cancelled"].includes(x.status)).length}</strong><span>En curso</span></article><article><strong>{orders.filter(x=>x.status==="completed").length}</strong><span>Completados</span></article><article><strong>{invoices.filter(x=>x.amountDueMinor>0).length}</strong><span>Facturas pendientes</span></article></section><div className="client-actions"><Link className="button" to="/client/transports">Ver transportes</Link><Link className="button button-secondary" to="/client/documents">Ver documentos</Link><Link className="button button-secondary" to="/client/invoices">Ver facturas</Link></div></>}</Frame>}

export function ClientTransports(){const [rows,setRows]=useState<ClientTransportListItem[]>([]);const [search,setSearch]=useState("");const [error,setError]=useState("");useEffect(()=>{void listClientTransports(search).then(setRows).catch(e=>setError(e instanceof Error?e.message:"Error"))},[search]);return <Frame><h1>Transportes</h1><label className="field">Buscar por número o referencia<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar transporte"/></label>{error?<State text={error}/>:rows.length===0?<State text="No hay transportes disponibles."/>:<div className="client-cards">{rows.map(row=><article className="client-card" key={row.id}><div><span className="status-badge">{row.statusLabel}</span><h2>{row.orderNumber}</h2></div><p>{row.origin??"Origen pendiente"} → {row.destination??"Destino pendiente"}</p><p>{row.plannedPickupAt?new Date(row.plannedPickupAt).toLocaleString():"Fecha pendiente"}</p><Link className="button" to={`/client/transports/${row.id}`}>Ver detalle</Link></article>)}</div>}</Frame>}

export function ClientTransportPage(){const {orderId}=useParams();const [value,setValue]=useState<ClientTransportDetail|null>(null);const [error,setError]=useState("");useEffect(()=>{if(orderId)void loadClientTransport(orderId).then(setValue).catch(e=>setError(e instanceof Error?e.message:"Acceso denegado"))},[orderId]);return <Frame>{error?<State text={error}/>:!value?<State text="Cargando transporte…"/>:<><Link to="/client/transports">← Transportes</Link><h1>{value.orderNumber}</h1><span className="status-badge">{value.statusLabel}</span><dl className="client-detail"><div><dt>Origen</dt><dd>{value.origin??"—"}</dd></div><div><dt>Destino</dt><dd>{value.destination??"—"}</dd></div><div><dt>Recogida prevista</dt><dd>{value.plannedPickupAt?new Date(value.plannedPickupAt).toLocaleString():"—"}</dd></div><div><dt>Entrega prevista</dt><dd>{value.plannedDeliveryAt?new Date(value.plannedDeliveryAt).toLocaleString():"—"}</dd></div></dl><h2>Mercancía</h2>{value.items.length?<ul>{value.items.map((x,i)=><li key={`${x.description}-${i}`}>{x.description} · {x.packages} bultos</li>)}</ul>:<p>Sin detalle compartido.</p>}<h2>Seguimiento</h2><ol className="client-timeline">{value.events.map(e=><li key={e.id}><strong>{timelineLabel(e.eventType)}</strong><time>{new Date(e.occurredAt).toLocaleString()}</time></li>)}</ol>{value.incidents.length>0&&<><h2>Incidencias compartidas</h2>{value.incidents.map(i=><article className="client-card" key={i.id}><h3>{i.title}</h3><p>{i.description}</p></article>)}</>}</>}</Frame>}

export function ClientDocuments(){const [rows,setRows]=useState<ClientDocumentItem[]>([]);const [error,setError]=useState("");useEffect(()=>{void listClientDocuments().then(setRows).catch(e=>setError(e instanceof Error?e.message:"Error"))},[]);async function download(id:string){try{window.location.assign(await createClientSignedUrl("document_url",id))}catch(e){setError(e instanceof Error?e.message:"Descarga no disponible")}}return <Frame><h1>Documentos</h1>{error&&<State text={error}/>}<div className="client-cards">{rows.map(x=><article className="client-card" key={x.id}><h2>{x.title}</h2><p>{x.documentType}</p><button className="button" onClick={()=>void download(x.id)}>Descargar</button></article>)}</div>{!error&&rows.length===0&&<State text="No hay documentos disponibles."/>}</Frame>}

export function ClientInvoices(){const [rows,setRows]=useState<ClientInvoiceListItem[]>([]);const [error,setError]=useState("");useEffect(()=>{void listClientInvoices().then(setRows).catch(e=>setError(e instanceof Error?e.message:"Error"))},[]);async function download(id:string){try{window.location.assign(await createClientSignedUrl("invoice_pdf_url",id))}catch(e){setError(e instanceof Error?e.message:"PDF no disponible")}}return <Frame><h1>Facturas</h1>{error&&<State text={error}/>}<div className="client-cards">{rows.map(x=><article className="client-card" key={x.id}><h2>{x.invoiceNumber}</h2><p>Total: {money(x.totalMinor,x.currencyCode)}</p><p>Pendiente: {money(x.amountDueMinor,x.currencyCode)}</p><p>Vencimiento: {x.dueDate??"—"}</p><button className="button" onClick={()=>void download(x.id)}>Descargar PDF</button></article>)}</div>{!error&&rows.length===0&&<State text="No hay facturas emitidas."/>}</Frame>}

export function ClientProfile(){const {access}=useAuth();return <Frame><h1>Mi perfil</h1><dl className="client-detail"><div><dt>Nombre</dt><dd>{access?.profile.displayName}</dd></div><div><dt>Teléfono</dt><dd>{access?.profile.phone??"—"}</dd></div><div><dt>Rol</dt><dd>{access?.effectiveRole==="client_admin"?"Administrador del cliente":"Consulta"}</dd></div></dl></Frame>}
function money(minor:number,currency:string){return new Intl.NumberFormat("es-ES",{style:"currency",currency}).format(minor/100)}
function timelineLabel(value:string){return ({"transport.planned":"Planificado","transport.pickup_arrived":"Llegada a recogida","transport.departed":"En tránsito","transport.destination_arrived":"Llegada a destino","transport.completed":"Entregado","pod.available":"POD disponible","incident.client_visible":"Incidencia"} as Record<string,string>)[value]??"Actualización"}
